### ISSUE TITLE
Issue with rails 3.1 rc4

### ISSUE THREAD

**Issue by trivektor** [geokit/geokit#29]
I got the following error when running geokit-gem

undefined local variable or method `acts_as_mappable'

Does this gem work with rails 3.1 rc4 yet?
